### model
model_name_or_path: /public/models/Qwen3-8B/
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
# dataset: sentencing_pk_math12k_train
template: qwen3_nothink
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
# output_dir: saves/qwen3-8b/lora-16-pk/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: sentencing_pk_math12k_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
